#port
server:
  port: 8095

#database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/project?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false
#jpa:
#  database: mysql
#  database-platform: org.hibernate.dialect.MySQL8Dialect
#  show-sql: true
#  hibernate:
#    format_sql : true
#    ddl-auto: create # ?? ??? ??

#thymeleaf
#thymeleaf:
#  cache: false
#    check-template-location: true
#    prefix: classpath:/templates/
#    suffix: .html
#    enabled: true
